import type { Metadata } from "next";
import "./globals.css";
import SessionButton from "@/components/SessionButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="sticky top-0 z-50 w-full bg-background border-b border-border flex items-center justify-between px-8 py-4">
          <span className="text-2xl font-bold tracking-tight">Kaffeekonsum-Tracker</span>
          <SessionButton />
        </header>
        {children}
      </body>
    </html>
  );
}
